// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7Sbj57PP81wRxmT-TkWyqaHSwUECoz4',
    appId: '1:66995660762:web:3647eb1e256bb6a34c42e3',
    messagingSenderId: '66995660762',
    projectId: 'malzemecim-21',
    authDomain: 'malzemecim-21.firebaseapp.com',
    storageBucket: 'malzemecim-21.firebasestorage.app',
    measurementId: 'G-8PBM72G0KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKhjRvoUBktLo2kBUsTOAXNkBDwj6thWw',
    appId: '1:66995660762:android:43c124fd7210821c4c42e3',
    messagingSenderId: '66995660762',
    projectId: 'malzemecim-21',
    storageBucket: 'malzemecim-21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFKnqIlvLqd82supBYMXdH1n6VUm--sME',
    appId: '1:66995660762:ios:05c41c399dca51514c42e3',
    messagingSenderId: '66995660762',
    projectId: 'malzemecim-21',
    storageBucket: 'malzemecim-21.firebasestorage.app',
    iosBundleId: 'com.example.malzemecim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7Sbj57PP81wRxmT-TkWyqaHSwUECoz4',
    appId: '1:66995660762:web:2ff8d572b127f8f34c42e3',
    messagingSenderId: '66995660762',
    projectId: 'malzemecim-21',
    authDomain: 'malzemecim-21.firebaseapp.com',
    storageBucket: 'malzemecim-21.firebasestorage.app',
    measurementId: 'G-04G6LZTTNR',
  );
}
